CREATE TABLE IF NOT EXISTS housekeeping_common.legacy_replica_path (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  creation_timestamp BIGINT NOT NULL,
  event_id VARCHAR(250) NOT NULL,
  path_event_id VARCHAR(250) NULL,
  path VARCHAR(4000) NOT NULL,
  PRIMARY KEY (id)
);
