name: build

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Init Coveralls
      shell: bash
      run: |
          FOO=${{ secrets.COVERALLS_REPO_TOKEN }}
          FOO=something
          echo FOO $FOO
          if [[ -z "${FOO}" ]]
          then
             echo "secret available"
             COVERALLS_SKIP=false
          else
             echo "secret not available"
             COVERALLS_SKIP=true
          fi
          echo set-output name=COVERALLS_SKIP::${COVERALLS_SKIP}
          echo ::set-output name=COVERALLS_SKIP::${COVERALLS_SKIP}
    - name: Hello world
      run: echo Hello world COVERALLS_SKIP - $COVERALLS_SKIP , from step ${{ steps.vars.outputs.COVERALLS_SKIP }}

