name: build

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Init Coveralls
      shell: bash
      run: |
          COVERALLS_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}
          if [[ -z "${COVERALLS_TOKEN}" ]];
          then
             echo "secret not available"
             COVERALLS_SKIP=true
          else
             echo "secret not available"
             COVERALLS_SKIP=false
          fi
          echo ::set-env name=COVERALLS_SKIP2::${COVERALLS_SKIP}
    - name: Hello world
      shell: bash
      run: echo "Hello world COVERALLS_SKIP - $COVERALLS_SKIP , COVERALLS_SKIP2 - $COVERALLS_SKIP2 , from step ${{ steps.vars.outputs.COVERALLS_SKIP }}"
   - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Run Maven Targets
      run:  echo "mvn package jacoco:report coveralls:report --batch-mode --show-version --activate-profiles coveralls -Dcoveralls.skip=$COVERALLS_SKIP2 -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}"

