name: build

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Hello world
      run: echo Hello world event path - $GITHUB_EVENT_PATH , workspace - $GITHUB_WORKSPACE , GITHUB_REF - $GITHUB_REF , GITHUB_HEAD_REF - $GITHUB_HEAD_REF , GITHUB_BASE_REF - $GITHUB_BASE_REF
      env:
        FIRST_NAME: Mona
        GITHUB_CONTEXT: ${{ toJson(github) }}
