name: build

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Hello world
      run: echo Hello world $FIRST_NAME $GITHUB_CONTEXT
      env:
        FIRST_NAME: Mona
        GITHUB_CONTEXT: ${{ toJson(github) }}
