name: build

on: [push, pull_request]

jobs:
  test:
    name: Package and run all tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Init Coveralls
      shell: bash
      run: |
          COVERALLS_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}
          if [[ -z "${COVERALLS_TOKEN}" ]];
          then
             echo "secret not available"
             COVERALLS_SKIP=true
          else
             echo "secret not available"
             COVERALLS_SKIP=false
          fi
          echo set-output name=COVERALLS_SKIP::${COVERALLS_SKIP}
          echo ::set-output name=COVERALLS_SKIP::${COVERALLS_SKIP}
    - name: Hello world
      shell: bash
      run: echo "Hello world COVERALLS_SKIP - $COVERALLS_SKIP , from step ${{ steps.vars.outputs.COVERALLS_SKIP }}"
